# Generated by Django 6.0.7 on 2026-09-04 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchool', '0002_rename_students_learners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_status', models.CharField(max_length=20)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_number', models.IntegerField(unique=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mySchool', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySchool.rooms')),
            ],
        ),
        migrations.DeleteModel(
            name='Learners',
        ),
    ]
