# Generated by Django 6.0.7 on 2026-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchool', '0003_rooms_tenant_delete_learners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='users',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_status',
            field=models.CharField(choices=[('vacant', 'vacant'), ('occupied', 'occupied')], default='vacant', max_length=20),
        ),
    ]
