# Generated by Django 6.1.1 on 2026-10-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchool', '0004_remove_rooms_users_alter_rooms_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_status',
            field=models.CharField(default='vacant', max_length=20),
        ),
    ]
