# Generated by Django 6.0.7 on 2026-10-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySchool', '0005_tenant_user_alter_rooms_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='room',
        ),
    ]
